### ISSUE TITLE
(spanish)como hago para que twrp reinicie en recovery al flashear con odin?

### ISSUE THREAD

**Issue by jaslerman** [TeamWin/twrpme#101]
hola

como hago para que twrp reinicie en modo recovery al terminar de flashear e inicie automaticamente en modo recovery?

tengo una archivo twrp para sm-g532m que al terminar el flash, inicia automaticamente al recovery sin necesidad de presionar ningun boton pero solo funciona con este modelo pero con otros no.

en sintesis lo que necesito es que al terminar de flashear y haga auto reboot en modo recovery automaticamente.-

**Comment by bigbiff** [comment]
Hello, we don't support this device. I would go to the source of your image for questions.
