### ISSUE TITLE
Pixel 3 boot failing on Android 11

### ISSUE THREAD

**Issue by kitsune7** [TeamWin/twrpme#109]
I rooted my phone on Android 10 with TWRP and Magisk and it was working great. But, I foolishly jumped the gun and let the OS convince me to automatically upgrade to Android 11. The OS works fine, but it's no longer rooted.

I've verified that the boot loader is still unlocked and I downloaded the latest .img file for the Pixel 3, but when I run `fastboot boot twrp-3.3.0-0-blueline.img` from the bootloader screen, I get the following output:

```
Sending 'boot.img' (65536 KB)                      OKAY [  1.968s]
Booting                                            FAILED (remote: 'Error verifying the received boot.img: Invalid Parameter')
fastboot: error: Command failed
```

Does TWRP Blueline version 3.3.0-0 work with Android 11? Is there something obvious that I'm missing here?

**Comment by wildcodefox** [comment]
No. Android 10 and 11 are not working as of right now. Apparently google did some fucky shit and its taking twrp a long time. rip

**Comment by bigbiff** [comment]
Nothing to do with twrp.me

**Comment by phodina** [comment]
Hello @bigbiff,

do you know what was the reason behind the image not booting?

I'm trying to run the mainline kernel, but the bootloader won't run the kernel, just says the same message as reported above.

**Comment by bigbiff** [comment]
Usually it means your firmware is incompatible with the boot image.

**Comment by phodina** [comment]
What do you mean by firmware? I'm attempting to run there the mainline kernel. Checked all the offset are the same.

https://gitlab.com/postmarketOS/pmaports/-/merge_requests/3932#note_1310400191

I don't have the USB C serial port to see bootloader messages. So I'm blind here. But there is probably some patch missing in the mainline that the TWRP kernel has.
