### ISSUE TITLE
Add Amazon's Fire TV Stick 2nd gen (tank)?

### ISSUE THREAD

**Issue by 7wells** [TeamWin/twrpme#113]
Hello! I just stumbled over this post:
https://forum.xda-developers.com/t/unlock-root-twrp-unbrick-fire-tv-stick-2nd-gen-tank.3907002/

The author of the tool (latest version at time of writing this is "amonet-tank-v1.2.2.zip") that roots Amazon's Fire TV Stick 2nd gen (tank), has included TWRP, but I do not know which version. I also understand that the TWRP team expressed caveats about "unofficial" (not endorsed) TWRP versions published by other. Hopefully, my issue/request/question here is neither rude, nor impolite towards anybody, or otherwise bad behaviour. 😊 

Is it possible to officially include Amazon's Fire TV Stick 2nd gen (tank) to the official TWRP development? Thanks for your kind consideration, many thanks for your great efforts and support of the community, and my best wishes to all of you for the new year 2021! 👍 

PS: I am not affiliated with the author of the aforementioned tool.

**Comment by 7wells** [comment]
@bigbiff 
Please accept my apologies for bothering you. Have you closed this because it is simply not feasible? Thanks for taking your time for a short reply.

**Comment by bigbiff** [comment]
I closed it due to it not being applicable to the twrpme website.

**Comment by 7wells** [comment]
Oh, yes, now I see it. Sorry for my mistake and thanks for opening my eyes. 😊

I see several Amazon device-related twrp repos but none of them for the Fire TV stick 2nd gen ("tank"). Do you have a recommendation where to post my question? Thank you so much.
