### ISSUE TITLE
Redmi 6A missing instructions

### ISSUE THREAD

**Issue by AvrahamTsaban** [TeamWin/twrpme#114]
[There are](https://twrp.me/xiaomi/xiaomiredmi6a.html) no instructins for the Fastboot Install Method. 
It is very simple and may be copied from the [8A page](https://twrp.me/xiaomi/xiaomiredmi8a.html).

**Comment by bigbiff** [comment]
Thanks, I have added the fastbootinstall macro to the markdown.
