### ISSUE TITLE
download with mobile browsers

### ISSUE THREAD

**Issue by Michas0206** [TeamWin/twrpme#115]
Again, download from mobile does not work as it should: Firefox want to save .img as .txt, and mobile's standardbrowser(s) does not save a file at all here.

(and the twrp app crashes here atm...)

Its  possible to download from pc - but its so ... - please make your homepage/download work with normal browsers. Nothing is changed in my referer, its standard Firefox and your hp has a problem.

Edit: changing / removing the ads would also be great - all these "download" buttons leading to pages that have nothing to do with twrp makes your page look very unsecure/unsafe/not trustworthy.

**Comment by TriDiscord** [comment]
If your browser doesn't download the img file properly, it's an issue with your browser. It works for all my devices, there's something wrong with your browser.

**Comment by bigbiff** [comment]
Download requires referral set on. We cannot control what ads Google serves. Ads are used to pay for hosting.
