### ISSUE TITLE
Copyright is outdated

### ISSUE THREAD

**Issue by 1Maxnet1** [TeamWin/twrpme#122]
On the website it still sais copyright is until 2020. You may want to update it to 2021.

Another solution would be to implement an auto-updating solution, to solve this issue forever.

**Comment by 1Maxnet1** [comment]
It is even incosistent among different mentions: Can find 2018, 2019 and 2020

**Comment by bigbiff** [comment]
It's a static built website, but I updated for this year: https://gerrit.twrp.me/c/twrpme/+/3801
