### ISSUE TITLE
dl.twrp.me doesn't work

### ISSUE THREAD

**Issue by nimoos** [TeamWin/twrpme#124]
when I click on the Primary (Americas) link, I redirect to dl.twrp.me and the link doesn't work

**Comment by Velosh** [comment]
> when I click on the Primary (Americas) link, I redirect to dl.twrp.me and the link doesn't work

Gerrit, Jenkins & Download Mirror of TeamWin is down, since yesterday.

**Comment by Velosh** [comment]
Any idea? @bigbiff

**Comment by bigbiff** [comment]
Site is back up.

**Comment by Velosh** [comment]
> Site is back up.

Thanks.
