### ISSUE TITLE
What if I replace the recovery.img from the MIUI FASTBOOT Rom!

### ISSUE THREAD

**Issue by SHITIJHALDER** [TeamWin/twrpme#126]
Recently my device got softbricked and I unbricked my device through FASTBOOT Rom ( Device name **Xiaomi Redmi 6 (Cereus)** . Now I saw my device all the .img file that contains **Recovery,Boot,Cust, System** so my question is what if I replace the inbuilt recovery with TWRP??? If I replace MIUI Recovery with TWRP then I don't think that we would be getting any problem. 
The main thing is that MIUI will think that TWRP is the default recovery of the device and hence no Encryption and Decryption problem will come!!! 

What do you think ? Comment now!!!

**Comment by bigbiff** [comment]
This project is for updates to the twrp.me website. Please ask these questions in your requisite device forum at xda developers.
