### ISSUE TITLE
Sort releases/versions by time instead of filename

### ISSUE THREAD

**Issue by Crystal-RainSlide** [TeamWin/twrpme#128]
Releases/versions are now: sorted by filename & compared by string,
instead of: sorted by release time & compared by time/unix timestamp as number,
so, if a part of the version numbers go higher than 10, the orders are disrupted.

With an older version sorted before a newer version,careless people would easily
download an older version instead of the lastest one, which is not ideal.

Along with fixing this, highlight the lastest release may also enhance usability.

---

Example: https://dl.twrp.me/ginkgo/,
where `twrp-3.5.2_10-2-ginkgo.img` goes below `twrp-3.5.2_9-_0_-ginkgo.img` and `twrp-3.5.2_9-_1_-ginkgo.img`.

**Comment by bigbiff** [comment]
Completed.
