### ISSUE TITLE
LG K11 looks not available.

### ISSUE THREAD

**Issue by migvel** [TeamWin/twrpme#131]
Hello I would like to install TWRP in a LG K11 but looks that it is not available yet.

I would appreciate any insight, either on how to find it or on how to create a new markdown.

Regards.

**Comment by bigbiff** [comment]
Are you going to maintain a version for this device?

**Comment by migvel** [comment]
It might depending upon the required work that would take to port the markdown.

Thanks.

**Comment by bigbiff** [comment]
Porting a markdown? I mean porting TWRP. I think this is just a device request so I am closing this issue as this area is not for device requests.
