### ISSUE TITLE
Nubia Z17 mini not in the devices list

### ISSUE THREAD

**Issue by mjarosie** [TeamWin/twrpme#132]
When searching for Nubia Z17 mini (device code: nx569j) it doesn't appear on the [list of supported devices](https://twrp.me/Devices/), but it's actually possible to download TWRP for it from here: https://eu.dl.twrp.me/nx569j/

That'd suggest that the devices search page is not showing all available devices.

**Comment by bigbiff** [comment]
No one is currently maintaining the device so the markdown was never added it seems.
