### ISSUE TITLE
Create own twrp

### ISSUE THREAD

**Issue by Fadooms** [TeamWin/twrpme#139]
Hello everyone I am looking for help to create custom twrp for my Tecno camon 17 pro phone. (256g rom 8g ram mediatek Helios g95 mt6587 android 11 root a/b partion). I don't have recovery.img but boot.img I saw it was compiled into boot.img and would like to know how to extract it or if there is a method to intall twrt recovery. thanks for the help

**Comment by bigbiff** [comment]
Please don't open device requests here.
