### ISSUE TITLE
twrp 3.0.0.0 not working on treltexx

### ISSUE THREAD

**Issue by NetworkPro** [TeamWin/twrpme#14]
twrp 3.0.0.0 not working on treltexx

black screen after power on

**Comment by MSF-Jarvis** [comment]
From the [release announcement](https://twrp.me/site/update/2016/02/05/twrp-3.0.0-0-released.html) :

>WARNING: This is our first release in a long time. We have a lot of new and somewhat aggressive changes in this new release. The changes to the graphics back-end may cause some devices to not boot up properly or have other display-related issues. If you are not in a position to reflash an older build of TWRP, then wait until you are or at least wait until others have tried the new version for your specific device. You don’t want to end up with a non-working recovery and have to wait several hours or days to get to a computer to be able to fix it.

**Comment by a2rh79** [comment]
Ccc

**Comment by NetworkPro** [comment]
Seems this is silently fixed.

This time I also cleaned all partitions before and after installing the img.

Thanks.

**Comment by strugee** [comment]
@NetworkPro if this is fixed, please close this issue.

Note also (for the future) that this is the TWRP website repository, so this issue was misfiled, anyway. You should have filed it in the proper device repository.
