### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Hakalle** [TeamWin/twrpme#141]
How can I contact bigbiff via e-mail? His e-mail is not working.

**Comment by bigbiff** [comment]
What email did you use? The best thing to use is Zulip: http://tiny.cc/TWRP-Zulip

**Comment by Hakalle** [comment]
Thank you, I'll contact you soon.
Sorry for anything.

**Comment by Hakalle** [comment]
@bigbiff for some reason I can't chat at Zulip, but I've pmed you (my display name: Enzo Aquino V.), if you can check it later.
