### ISSUE TITLE
Bad signatures on TeamWin GPG key - Flame

### ISSUE THREAD

**Issue by danielrocher** [TeamWin/twrpme#144]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: flame
**TWRP version**: 3.7.0_12-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
`gpg --verify twrp-3.7.0_12-0-flame.img.asc `

#### WHAT IS THE EXPECTED RESULT?

All key signatures should be valid, even if not trusted.

#### WHAT HAPPENS INSTEAD?

```bash
sha256sum -c twrp-3.7.0_12-0-flame.img.sha256 
twrp-3.7.0_12-0-flame.img: OK

gpg --verify twrp-3.7.0_12-0-flame.img.asc 
gpg: assuming signed data in 'twrp-3.7.0_12-0-flame.img'
gpg: Signature made Tue Oct 11 02:53:27 2022 CEST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```

#### ADDITIONAL INFORMATION

with version `3.6.2_11-0`, no error :
```bash
sha256sum -c twrp-3.6.2_11-0-flame.img.sha256 
twrp-3.6.2_11-0-flame.img: OK

gpg --verify twrp-3.6.2_11-0-flame.img.asc 
gpg: assuming signed data in 'twrp-3.6.2_11-0-flame.img'
gpg: Signature made Fri Jun 10 01:29:41 2022 CEST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
```

**Comment by bigbiff** [comment]
This has been fixed. Thanks for letting us know.
