### ISSUE TITLE
BAD signature for twrp-3.7.0_9-0-a3xelte.img

### ISSUE THREAD

**Issue by rdlr-at-github** [TeamWin/twrpme#151]
Signature for "twrp-3.7.0_9-0-a3xelte.img" on the download servers seems to be wrong:
```
[reinhard@Void TWRP]$ gpg --verify twrp-3.7.0_9-0-a3xelte.img.asc 
gpg: assuming signed data in 'twrp-3.7.0_9-0-a3xelte.img'
gpg: Signature made Tue 11 Oct 2022 02:11:39 AM CEST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```
Could you please check (and correct)!
Thanks in advance ...

**Comment by bigbiff** [comment]
Thanks for reporting the issue. It is now fixed:
jenkins@ns103310:/www/dl.twrp.me/a3xelte$ gpg --verify twrp-3.7.0_9-0-a3xelte.img.asc
gpg: assuming signed data in 'twrp-3.7.0_9-0-a3xelte.img'
gpg: Signature made Sat 11 Feb 2023 10:12:27 PM UTC
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
