### ISSUE TITLE
bad signature twrp-3.7.0_9-0-a5y17lte

### ISSUE THREAD

**Issue by peaceful-dreamer** [TeamWin/twrpme#152]
exact same problem as here [https://github.com/TeamWin/twrpme/issues/145](https://github.com/TeamWin/twrpme/issues/145), but with the a5y17lte device.

**Comment by bigbiff** [comment]
Thanks, this is fixed:

jenkins@ns103310:/www/dl.twrp.me/a5y17lte$ gpg --verify twrp-3.7.0_9-0-a5y17lte.img.asc
gpg: assuming signed data in 'twrp-3.7.0_9-0-a5y17lte.img'
gpg: Signature made Wed 01 Mar 2023 02:23:47 AM UTC
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
