### ISSUE TITLE
Who recieves ad / donation revenue?

### ISSUE THREAD

**Issue by jkdf2** [TeamWin/twrpme#17]
Just curious :smiley:

**Comment by Dees-Troy** [comment]
Not that it's anyone's business, but bigbiff and I split what's left of the ad revenue after paying for hosting and other related Web services costs. The ad revenue isn't exactly significant. It's certainly not going to allow anyone to quit their full-time job to work on TWRP. Donations make up an even smaller amount of income.

**Comment by jkdf2** [comment]
I can't speak for others, but I enjoy financial transparency in open source projects. Knowing that it goes to you and @bigbiff, I've made a small donation. Thanks for your work.
