### ISSUE TITLE
where can I request a new recovery?

### ISSUE THREAD

**Issue by cjnthn** [TeamWin/twrpme#18]
I have an Alcatel One Touch Fierce XL, and currently there's no recovery available for it. I love your recovery apps, so how can I put a request in for one to possibly be made?

**Comment by MSF-Jarvis** [comment]
Nowhere, we don't build for devices on request.

**Comment by ashusagar** [comment]
Hi!
I need recovery for my Infoucs M370i... Please help me and make a recovery for my phone.
Thank you.
Sagar

**Comment by MSF-Jarvis** [comment]
That's not how the process goes, you cannot just ask for shit. Learn and build

**Comment by ashusagar** [comment]
Ok then tell me how built recovery atleast give me any link where can i learn...

**Comment by MSF-Jarvis** [comment]
Google for it

**Comment by ashusagar** [comment]
ok

**Comment by MSF-Jarvis** [comment]
@ashusagar close this issue
