### ISSUE TITLE
In some situations HTML is served instead of the recovery image

### ISSUE THREAD

**Issue by dkbg** [TeamWin/twrpme#30]
Attempting to download a recovery image by passing the URL to wget or curl downloads HTML. Specifically, it seems to give the overview page for the download (e.g. https://dl.twrp.me/athene/twrp-3.1.0-0-athene.img.html). Also, if one removes the ".html" from the end of the URL, Firefox (50.1.0) will happily load the exact same page and not prompt a download. I've tried with a couple of different images and they all seem to have the same problem. Clicking on the link itself works as expected although Firefox seems to think the file is text.

For example, trying to download https://dl.twrp.me/athene/twrp-3.1.0-0-athene.img with wget serves up a 7.1KB Web page.

This post on Google Plus seems to describe the same problem: https://plus.google.com/114004832310481604983/posts/7SJYcB1pJB2

Seems like a Web server misconfiguration.

**Comment by dkbg** [comment]
Just realised this is basically a duplicate of #28.

**Comment by bigbiff** [comment]
We enforce referrer.
