### ISSUE TITLE
Translate twrp 

### ISSUE THREAD

**Issue by yabghu** [TeamWin/twrpme#31]
Hello I want to translate this app to Uyghur language.How can I contact with you?

**Comment by Mattwmaster58** [comment]
Check this out: https://crowdin.com/project/team-win-recovery-project

**Comment by yabghu** [comment]
I can not creat Uyghur language translation file.Can you help me creat Uyghur language on crowdin .I will translate it.

**Comment by Mattwmaster58** [comment]
It looks like the Uyghur language is not in high demand. You will probably have to contact Ethan Yonker (https://crowdin.com/mail/compose/Dees-Troy) in order to add it.

**Comment by bigbiff** [comment]
Hello, you can see translation commits in our github repository.
