### ISSUE TITLE
serranoveltexx: flashing twrp-3.0.2-0 gives errors with odin and heimdall

### ISSUE THREAD

**Issue by Klausthorn** [TeamWin/twrpme#40]
When I'm using Odin3 v3.12 I get:

> FAIL! (Size)

When I'm using Heimdall v1.4.0: 

> ERROR: Failed to confirm end of file transfer sequence!

Questions:

- What can I do to work around the problem?
- What is the cause?
- I have Samsung Galaxy S4 mini, not branded, Germany. LineageOS calls it serranoltexx, you call it serranoveltexx... is it the same?

Additional Info:

- I confirmed the md5sum for twrp 3.0.2-0
- I also tried twrp 2.8.7.1 with Odin, same error.

**Comment by bigbiff** [comment]
Please leave device issues on the device repository.
