### ISSUE TITLE
Problem with naming device subsites/images

### ISSUE THREAD

**Issue by hippi-viking** [TeamWin/twrpme#46]
Hello,

Thanks for all the great work guys!
If time allows could you please change the way the actual images are linked on the website? Somehow android brosers (or even curl) are unable to correctly follow the link and always come up with the image download site itself (which is named the esact same way as the image plus a .html extension attached to the end). So practically you need an other device (eg. pc) to download the image and then transfer it to the phone/tablet/whatever.

Cheers,
Istvan

**Comment by bigbiff** [comment]
This is by design. Sorry for the inconvenience.
