### ISSUE TITLE
bq namek compile twrp 3.2.0 i like to compile latest 3.2.1 but it is not avaible in github. in compile it comment this external/libcxx/include/memory:3132: error: undefined reference to 'MinuiBackendAdf::MinuiBackendAdf()'

### ISSUE THREAD

**Issue by peturbg** [TeamWin/twrpme#48]
When it try to compile bq namek latest version 3.2.0 " with like to install latest 3.2.1 version of twrp but it is not avaible in github " compiling it comment this error:
in boardconfig.mk it has TARGET_HW_DISK_ENCRYPTION := false and again it comment about this: FAILED: /bin/bash -c "prebuilts/misc/linux-x86/ccache/ccache prebuilts/clang/host/linux-x86/clang-2690385/bin/clang++ -nostdlib -Bstatic -static -Wl,--gc-sections -o /home/peturbg/BLADE/out/target/product/namek/obj/EXECUTABLES/healthd_intermediates/LINKED/healthd -L/home/peturbg/BLADE/out/target/product/namek/obj/lib /home/peturbg/BLADE/out/target/product/namek/obj/lib/crtbegin_static.o -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--icf=safe -Wl,--hash-style=gnu -Wl,--no-undefined-version -Wl,--no-fix-cortex-a8 -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -Wl,--exclude-libs,libunwind_llvm.a -Wl,--no-undefined /home/peturbg/BLADE/out/target/product/namek/obj/EXECUTABLES/healthd_intermediates/healthd.o -Wl,--whole-archive -Wl,--no-whole-archive /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libhealthd.cm_intermediates/libhealthd.cm.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/libhealthd_internal.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libbatterymonitor_intermediates/libbatterymonitor.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libbatteryservice_intermediates/libbatteryservice.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libbinder_intermediates/libbinder.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libminui_intermediates/libminui.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libpng_intermediates/libpng.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libz_intermediates/libz.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libutils_intermediates/libutils.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libbase_intermediates/libbase.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libcutils_intermediates/libcutils.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/liblog_intermediates/liblog.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libm_intermediates/libm.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libc++_static_intermediates/libc++_static.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libunwind_llvm_intermediates/libunwind_llvm.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libm_intermediates/libm.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libdl_intermediates/libdl.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a -Wl,--start-group /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libc_intermediates/libc.a /home/peturbg/BLADE/out/target/product/namek/obj/STATIC_LIBRARIES/libc_intermediates/libc.a prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/lib/libatomic.a prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/libgcc.a -Wl,--end-group /home/peturbg/BLADE/out/target/product/namek/obj/lib/crtend_android.o"
external/libcxx/include/memory:3132: error: undefined reference to 'MinuiBackendAdf::MinuiBackendAdf()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[ 99% 2376/2385] host C: mkbootfs <= system/core/cpio/mkbootfs.c
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (02:25 (mm:ss)) #### 

In boardconfig.mk it has TARGET_HW_DISK_ENCRYPTION := false but too it comment error. Include it try to compile with busybox but it comment for microcom.c dissapointet. In 21 century and linux android continues fail. Linux andorid don't have support for old smartphones and it only have for new mobile phones. When error arrive it is impossible to fix it, if you are not developer of the program. And developers of the program can be away for 1 months, 1 years or include she will not use anymore. In linux android they use include <cryptblahblah.c> and when it start compile it will fail, becouse linux android is instable, bad. write complete path to directory and when it fail write how it can be resolved.

Include twrp github is for latest versions and they don't have latest version. there is new version and no source code.

**Comment by bigbiff** [comment]
According to our jenkins log, we compile namek in omni-6.0 under the android-6.0 branch here: https://github.com/TeamWin/android_device_bq_namek
