### ISSUE TITLE
TWRP installation with Odin

### ISSUE THREAD

**Issue by John3620** [TeamWin/twrpme#5]
Hi,
There is a step in Odin Install Method that I don't understand ! :
"Note many devices will replace your custom recovery automatically during first boot.
To prevent this, use Google to find the proper key combo to enter recovery. 
After typing fastboot reboot, hold the key combo and boot to TWRP."
I know the proper key combo to enter recovery on my device but what about "typing fastboot reboot" ??
What is it ? Can someone explain me clearly what to do just after the installation of TWRP with Odin.

**Comment by nongrus** [comment]
Thank'z

**Comment by blair39999** [comment]
Thank

**Comment by Mattwmaster58** [comment]
Samsung devices don't have fastboot. Just boot into recovery, then reboot to system.

**Comment by bigbiff** [comment]
Answered above.
