### ISSUE TITLE
Download's link loop

### ISSUE THREAD

**Issue by pr-nizar** [TeamWin/twrpme#6]
The download's link for [twrp-2.8.6.0-titan.img](http://dl.twrp.me/titan/twrp-2.8.6.0-titan.img) points to the same page.

**Comment by The-Compiler** [comment]
While I can download that file just fine, I get a loop for [twrp-2.8.6.0-xt1032.img](https://dl.twrp.me/xt1032/twrp-2.8.6.0-xt1032.img). It seems to work fine with Firefox and Chromium, but not with any WebKitGTK or QtWebKit based browser.

Some logs: https://github.com/The-Compiler/qutebrowser/issues/1266#issuecomment-174838449

**Comment by Dees-Troy** [comment]
Our website uses a referrer to help ensure that people don't directly link to our downloads without seeing the ads.
