### ISSUE TITLE
 Avoid multiple, costly round trips to any origin

### ISSUE THREAD

**Issue by BO41** [TeamWin/twrpme#61]
Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins.  [learn more](https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect)

Origin | Potential Savings
-- | --
https://www.gstatic.com | 430 ms
https://ssum-sec.casalemedia.com | 410 ms
https://cms.quantserve.com | 380 ms
https://fcmatch.youtube.com | 380 ms
https://fonts.googleapis.com | 370 ms
https://odr.mookie1.com | 340 ms
https://encrypted-tbn3.gstatic.com | 320 ms
https://fcmatch.google.com | 300 ms

**Comment by bigbiff** [comment]
preconnect to these sites have been added to the head.html template.
