### ISSUE TITLE
no favicon

### ISSUE THREAD

**Issue by BO41** [TeamWin/twrpme#62]
the page does not seem to have a favicon.

it is always nice to have an favicon to make the page better looking and easier to distinguish to others in the tab overview.

https://en.wikipedia.org/wiki/Favicon

something like
```html
<link rel="shortcut icon" href="/images/favicon.ico">
```

**Comment by bigbiff** [comment]
Added favicon to root of site.

**Comment by BO41** [comment]
not the best solution, but **way better** than nothing :+1:
