### ISSUE TITLE
Use compression

### ISSUE THREAD

**Issue by BO41** [TeamWin/twrpme#64]
>Configure your server to send data in a compressed format to reduce transfer times. For compressible files, compression can reduce the amount of data that needs to be sent by around 70% for only a small amount of configuration effort. Text-based data formats such as HTML, CSS, JavaScript, plain text, XML, JSON and SVG should almost always be sent with compression enabled. However, we recommend only compressing responses above 1,000 bytes in size as compressing small files can actually increase the response size and compression has a server CPU overhead. To confirm your server is sending a URL response in a compressed format, you should 1) verify the Content-Encoding response header is being returned and 2) check the value of that header is set to the name of a compression scheme such as gzip, deflate or br. If you're checking from your own machine that runs antivirus software, be aware there's been cases where HTTP scanning features have been found to disable compression before responses reach your browser. Also, it isn't unusual to see misconfigured servers which compress some compressible file types like HTML but forget to do it for others like CSS so be on the look out for this.

not really important for this page, but would also not hurt

**Comment by bigbiff** [comment]
Gzip is turned on and verified.
