### ISSUE TITLE
Feature request: Dark theme Twrp option. Why there has be extra another app for this only?

### ISSUE THREAD

**Issue by PranavBhattarai** [TeamWin/twrpme#76]
Developers have made a black themed twrp app. If Twrp gives the user the native option to view it in Dark instead of White only, it would have been easier in eyes &  battery. Because the brightness level in Twrp is usually like 100% by default, so dark option would have made life easier. 

Dark mode is a trending feature these days. Why the original app is lacking behind!?

**Comment by bigbiff** [comment]
This is for twrp,me website issues only.
