### ISSUE TITLE
Flashing Zip Failure TWRP 2.8.6

### ISSUE THREAD

**Issue by k9kishore** [TeamWin/twrpme#8]
I am a newbie to GitHub... so, please excuse me if this is not the right place for this issue. I have just (first time with rooting etc.) installed TWRP 2.8.6 (seems to be working fine) on a Moto X 2013 (XT-1052). However, whenever I try to flash CM11/12 from zip file I get the message "Error flashing zip file" and failed as the outcome. Any help would be appreciated.

**Comment by strugee** [comment]
@k9kishore sounds like a corrupted ZIP file. In any case, this is the wrong place to file your issue. You should file it either in the main TWRP codebase repository, or in the repository that holds your particular device's support files.
