### ISSUE TITLE
Signature mismatch on twrp-3.3.1-0-hlte.img

### ISSUE THREAD

**Issue by UnixRonin** [TeamWin/twrpme#80]
Posted signatures on https://dl.twrp.me/hlte/twrp-3.3.1-0-hlte.img.html:
3e780d2261bf49ebb6f3f5ad7afbf63a  twrp-3.3.1-0-hlte.img
d66c0d66cca97ddf67eaeef605a5ed5394b522e53c21c03c8df59a3b87d841a0  twrp-3.3.1-0-hlte.img

Actual current checksums today:
d73a7efe2b0daa967bc301fac370e052  twrp-3.3.1-0-hlte.img
1739f9f996a9e898961b39e08ea3ef54d710dc3560d73d20347de7f78a0345f9  twrp-3.3.1-0-hlte.img

**Comment by bigbiff** [comment]
Please verify your download. Everything is OK:
bigbiff@build:/www/dl.twrp.me/hlte$ cat twrp-3.3.1-0-hlte.img.md5
3e780d2261bf49ebb6f3f5ad7afbf63a  twrp-3.3.1-0-hlte.imgbigbiff@build:/www/dl.twrp.me/hlte$
bigbiff@build:/www/dl.twrp.me/hlte$ md5sum twrp-3.3.1-0-hlte.img
3e780d2261bf49ebb6f3f5ad7afbf63a  twrp-3.3.1-0-hlte.img
