### ISSUE TITLE
Mobile: Advertisement banner covers drop-down menu

### ISSUE THREAD

**Issue by someone755** [TeamWin/twrpme#9]
On a mobile device, the drop-down menu seems to be placed under the ad banner, so the only clickable link is the contact one. Unless the user dismisses the ad (either by selecting "ad covers page" or by using an ad-blocker), the menu is useless.

**Comment by easyaspi314** [comment]
FIX (dunno how do do this in SCSS)

Add `z-index: 1;` in `.site-nav` for `@media screen and (max-width: 600px)`

**Comment by someone755** [comment]
It's still there for me: http://i.imgur.com/HfhL980.png I again had to dismiss the ad before the menu was useful again.

**Comment by someone755** [comment]
Oh never mind your PR hasn't been merged. Github on mobile really is a pain. 

I think you should be submitting this through the Gerrit though.

**Comment by bigbiff** [comment]
Please submit to gerrit.twrp.me/twrpme branch test so we can try and push it to https://test.twrp.me

If it works you can push it to master branch on twrpme gerrit project so we can add it to the main site.

**Comment by easyaspi314** [comment]
How do I do that?

**Comment by bigbiff** [comment]
Please check out a Gerrit how to on submitting code to our instance.

**Comment by bigbiff** [comment]
Please check out a Gerrit how to on submitting code to our instance.

**Comment by bigbiff** [comment]
Please check out a Gerrit how to on submitting code to our instance.

**Comment by bigbiff** [comment]
Please check out a Gerrit how to on submitting code to our instance.

**Comment by bigbiff** [comment]
Please check out a Gerrit how to on submitting code to our instance.

**Comment by easyaspi314** [comment]
Just want to let you know that you sent 5 comments.

**Comment by bigbiff** [comment]
Yeah sorry, I deleted them here but I know they sent out emails on them. For some reason when I hit comment, it published the comment, but didn't show it to me until I refreshed the page.
