### ISSUE TITLE
404 Error on TWRP website

### ISSUE THREAD

**Issue by 1Maxnet1** [TeamWin/twrpme#90]
I found a broken Link in https://github.com/TeamWin/twrpme/blob/master/_samsung/samsunggalaxytrend.markdown . The device tree doesn't exist anymore. I didn't find another one on github, if so I woud have made a PR to replace it with the actual one.

Edit I found the new one: https://github.com/TeamWin/android_device_samsung_kyleve

**Comment by bigbiff** [comment]
Thanks for the report. The link has been fixed.
