### ISSUE TITLE
Not getting verification for email on gerrit

### ISSUE THREAD

**Issue by raza231198** [TeamWin/twrpme#96]
I'm not getting verification for email on gerrit. But it shows verification email sent.
![Screenshot_20191205-181011143](https://user-images.githubusercontent.com/37952910/70236240-915df100-178a-11ea-9394-ccbbf40a505a.jpg)

**Comment by bigbiff** [comment]
Hi, I manually added your email. The new IP we received for emails is on the SBL and I have been unsuccessful at getting off the list. I want to route our email through our EU host eventually and see if we can get email sent again. Sorry for the inconvenience. Please close this issue if this works for you.

**Comment by raza231198** [comment]
@bigbiff Thanks for adding my email.

still email is not sending
