### ISSUE TITLE
still no reply from teamwin

### ISSUE THREAD

**Issue by raza231198** [TeamWin/twrpme#99]
I have applied for Official TWRP for Zenfone Max M1 since months ago on https://twrp.me/contactus/ and also submitted patch to create markdown on gerrit https://gerrit.twrp.me/c/twrpme/+/1649 but still no reply 🙄🙄

**Comment by bigbiff** [comment]
Hello, can you tell me the last TWRP test build from this device is ready to go? Just making sure everything was OK.

**Comment by raza231198** [comment]
@bigbiff yes https://github.com/raza231198/android_device_asus_X00P-twrp
